#!/bin/env python3

from fonctions import readconf
import fonctions

conf_file = "minmax.conf"

config = readconf(conf_file)

if config["read"]=="keyboard":
    ...
elif config["read"]=="arg":
    ...
elif config["read"]=="file":
    ...
    if "datafile" in config:
        ...
    else:
        ...
    ...

if (config["search"]=="min"):
    ...
elif (config["search"]=="max"):
    ...
else:
    ... 